try{
    let a = 0;
    console.log(program)
    console.log("successfully Run");
}
catch(err){
    console.log("this is an Error")
    console.log(p)
}

// finally used to clean-ups 
finally{
    console.log("finally")
}
